name: ecomers_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  shared_preferences: ^2.5.1
  pin_code_fields: ^8.0.1
  get: ^4.6.6
  carousel_slider: ^5.0.0
  logger: ^2.5.0
  http: ^1.2.2
  cached_network_image: ^3.3.0
  intl: ^0.18.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/features/product/controller/